In [1]:
import pandas as pd

In [3]:
ad=pd.read_csv('admissions.csv')
ad.head()

,admission_id,patient_id,admit_date,discharge_date,los_days,admit_type,ward_type,hospital_id,discharge_type,num_procedures,charlson_index,hba1c,creatinine,haemoglobin,systolic_bp,readmitted_30d,readmitted_7d
0,bcb311d6-0808-498f-8ae1-11abe1fbc08e,6960d399-8398-4db4-9a90-0b329b81bc2b,2024-01-23,2024-01-27,4,Elective,General,b22e7b51-2ea6-4611-a8e5-d3d24ec779d8,Recovered,0,0,6.3,0.86,16.2,157,0,0
1,996ac6db-a192-46a0-b536-503a1c57994b,ec1999d4-f097-4881-91a5-6f9b1f8dac78,2019-11-18,2019-11-19,1,OPD,General,8b1e01b7-9f0e-413f-b330-454d271a5c6e,Recovered,1,0,5.2,1.23,13.1,156,0,0
2,cc4849fa-b740-487b-beda-3086a18273c0,ed56abac-a0ba-44db-a816-b5da4183b9b5,2019-11-22,2019-11-27,5,Emergency,General,eae7c9ec-65c8-4d48-92f3-7da7b3e2b227,Recovered,0,2,5.6,0.67,10.9,130,1,0
3,b38cdd03-165c-428c-b221-9f1d4cf8bdeb,90c335d5-dd71-46c8-acd2-656653f421c6,2020-03-05,2020-03-16,11,Emergency,ICU,df4431ea-1acf-4e77-963c-6173e9787151,Recovered,1,2,4.7,1.40,8.8,159,1,0
4,6a154ec0-92cc-43f5-ada5-ede0a600ce9e,694988e8-9ef5-43e8-aefe-c6b98b1e96fe,2018-05-30,2018-06-04,5,Emergency,General,8b1e01b7-9f0e-413f-b330-454d271a5c6e,Recovered,1,5,5.0,0.94,11.3,173,1,0

In [5]:
ad.shape

(120000, 17)

In [6]:
ad.columns.tolist()

['admission_id',
 'patient_id',
 'admit_date',
 'discharge_date',
 'los_days',
 'admit_type',
 'ward_type',
 'hospital_id',
 'discharge_type',
 'num_procedures',
 'charlson_index',
 'hba1c',
 'creatinine',
 'haemoglobin',
 'systolic_bp',
 'readmitted_30d',
 'readmitted_7d']

In [7]:
ad.isnull().sum()

admission_id      0
patient_id        0
admit_date        0
discharge_date    0
los_days          0
admit_type        0
ward_type         0
hospital_id       0
discharge_type    0
num_procedures    0
charlson_index    0
hba1c             0
creatinine        0
haemoglobin       0
systolic_bp       0
readmitted_30d    0
readmitted_7d     0
dtype: int64

In [8]:
ad['admission_id'].duplicated().sum()

np.int64(0)

In [11]:
ad['admit_date'] = pd.to_datetime(ad['admit_date'])
ad['discharge_date'] = pd.to_datetime(ad['discharge_date'])
ad[['admit_date', 'discharge_date']].dtypes

admit_date        datetime64[us]
discharge_date    datetime64[us]
dtype: object

In [12]:
(ad['discharge_date'] < ad['admit_date']).sum()

np.int64(0)

In [13]:
(ad['los_days'] < 0).sum()

np.int64(0)

In [14]:
ad['los_days'].describe()

count    120000.000000
mean          6.852708
std           5.708269
min           1.000000
25%           3.000000
50%           5.000000
75%           9.000000
max          90.000000
Name: los_days, dtype: float64

In [16]:
calculated_los = (
    ad['discharge_date'] - ad['admit_date']
).dt.days 

(ad['los_days'] != calculated_los).sum()

np.int64(0)

In [18]:
ad['admit_type'].value_counts()

admit_type
Emergency    66540
Elective     37853
OPD          15607
Name: count, dtype: int64

In [19]:
ad['ward_type'].value_counts()

ward_type
General    76768
ICU        20833
HDU        15907
NICU        6492
Name: count, dtype: int64

In [20]:
ad['ward_type'].unique()

<StringArray>
['General', 'ICU', 'HDU', 'NICU']
Length: 4, dtype: str

In [21]:
ad['discharge_type'].value_counts()

discharge_type
Recovered    87420
LAMA         15429
Referred      9738
Expired       7413
Name: count, dtype: int64

In [22]:
ad[['num_procedures', 'charlson_index']].describe()

       num_procedures  charlson_index
count   120000.000000   120000.000000
mean         1.523742        1.894858
std          1.542197        1.610380
min          0.000000        0.000000
25%          0.000000        0.000000
50%          1.000000        2.000000
75%          2.000000        3.000000
max         15.000000        6.000000

In [23]:
(ad[['num_procedures', 'charlson_index']] < 0).sum()

num_procedures    0
charlson_index    0
dtype: int64

In [24]:
ad[['hba1c', 'creatinine', 'haemoglobin', 'systolic_bp']].describe()

               hba1c     creatinine    haemoglobin    systolic_bp
count  120000.000000  120000.000000  120000.000000  120000.000000
mean        5.869862       1.070463      11.840079     134.628075
std         1.061662       0.896135       2.171929      20.756544
min         4.000000       0.400000       4.000000      70.000000
25%         5.300000       0.770000      10.400000     120.000000
50%         5.700000       0.910000      11.900000     134.000000
75%         6.100000       1.100000      13.300000     148.000000
max        14.300000      15.000000      18.000000     220.000000

In [25]:
ad[['readmitted_7d', 'readmitted_30d']].value_counts()

readmitted_7d  readmitted_30d
0              0                 105790
               1                  13204
1              1                   1006
Name: count, dtype: int64

In [29]:
ad['readmitted_7d_label'] = ad['readmitted_7d'].map({
    0: 'No',
    1: 'Yes'
})

ad['readmitted_30d_label'] = ad['readmitted_30d'].map({
    0: 'No',
    1: 'Yes'
})

In [30]:
ad.to_csv("admissions_cleaned.csv", index=False)