In [2]:
import pandas as pd

In [3]:
data=pd.read_csv('patients.csv')
data.head(20)

,patient_id,age,gender,state,bpl_card,insurance_type,comorbidity_count,prev_admissions
0,2b179f89-9af7-45cf-86b4-3e01a47a3b7b,36,F,Telangana,False,Private,0,0
1,ecaeb9f3-d263-4712-b9b6-3312af5626ca,56,F,Uttar Pradesh,False,ESI,0,0
2,0160a5b6-877e-41e6-b84a-a2a51b367a36,67,F,Telangana,False,ESI,3,0
3,216875fa-b49d-4c47-8c8d-7191ba34ac06,53,M,Haryana,False,Ayushman,3,0
4,a2f3181d-e3f2-4fd3-8057-05a492ffcfb2,60,M,Maharashtra,True,Ayushman,4,1
5,7df7236c-d33b-4d0d-8e97-6fdd71fc3d05,39,F,Uttar Pradesh,True,Private,0,0
6,ab3bda6c-05df-4f4f-a6b2-c98e7dfcf336,34,M,Karnataka,True,ESI,1,1
7,cabcba57-999c-4197-816d-3856a9dfde4b,68,M,Bihar,True,Ayushman,1,2
8,fab45ba3-9100-4861-8d09-f4d675daefb1,46,M,Tamil Nadu,False,Ayushman,0,0
9,0a422c4d-0e1c-4dea-b4a4-b85a0eec5402,70,M,Andhra Pradesh,False,NaN,4,0
10,abfd52a8-8875-4b53-8b2e-0cc46a9cda9b,68,M,Tamil Nadu,False,NaN,2,0
11,69c9ab70-ab74-495d-b210-4686fc5b10e8,65,M,Maharashtra,False,Private,4,0
12,232f237b-e1c7-46a7-88f1-99f3c9573d0b,12,M,Telangana,True,NaN,0,0
13,33305070-7720-41b5-bf55-8f170c15cb03,61,Other,Maharashtra,False,ESI,2,1
14,fbf560e9-b985-4c43-889e-38b6009b1210,11,F,Gujarat,False,NaN,0,1
15,a34ce3d3-0957-4107-8c05-cc6da905a70e,47,F,Maharashtra,False,NaN,1,0
16,56e71b42-daf1-47f3-bab8-e17f7c0d994a,68,F,Gujarat,True,Ayushman,2,3
17,271c0669-81f6-41a5-b6c8-7fa0bba17eaf,81,M,Uttar Pradesh,False,ESI,1,0
18,f2c72230-8142-47ec-89b1-29c8a2ae42dd,68,M,Punjab,True,NaN,1,0
19,7c47edd5-39d1-426d-8fb4-6b6ea1d463d8,47,F,Gujarat,True,Ayushman,1,1

In [5]:
data['patient_id'].duplicated().sum()

np.int64(0)

In [6]:
data.isnull().sum()

patient_id               0
age                      0
gender                   0
state                    0
bpl_card                 0
insurance_type       24715
comorbidity_count        0
prev_admissions          0
dtype: int64

In [10]:
data['insurance_type']=data['insurance_type'].fillna('Unknown')
data.isnull().sum()

patient_id           0
age                  0
gender               0
state                0
bpl_card             0
insurance_type       0
comorbidity_count    0
prev_admissions      0
dtype: int64

In [15]:
data['gender'] = data['gender'].replace({
    'M': 'Male',
    'F': 'Female'
})
data['gender'].value_counts()

gender
Male      44190
Female    41361
Other       849
Name: count, dtype: int64

In [22]:
print(data['age'].describe())
data[data['age'] < 0]
data[data['age'] > 120]

count    86400.000000
mean        48.000405
std         21.690553
min          0.000000
25%         36.000000
50%         51.000000
75%         63.000000
max         95.000000
Name: age, dtype: float64

Empty DataFrame
Columns: [patient_id, age, gender, state, bpl_card, insurance_type, comorbidity_count, prev_admissions]
Index: []

In [24]:
data['age_group'] = pd.cut(
    data['age'],
    bins=[-1, 17, 35, 50, 65, 120],
    labels=['Child', 'Young Adult', 'Adult', 'Middle-aged', 'Senior']
)
data['age_group'].value_counts()

age_group
Middle-aged    25019
Adult          21841
Senior         18186
Child          11685
Young Adult     9669
Name: count, dtype: int64

In [26]:
data[['age', 'age_group']].head(20)

    age    age_group
0    36        Adult
1    56  Middle-aged
2    67       Senior
3    53  Middle-aged
4    60  Middle-aged
5    39        Adult
6    34  Young Adult
7    68       Senior
8    46        Adult
9    70       Senior
10   68       Senior
11   65  Middle-aged
12   12        Child
13   61  Middle-aged
14   11        Child
15   47        Adult
16   68       Senior
17   81       Senior
18   68       Senior
19   47        Adult

In [28]:
data['comorbidity_count'].describe()
data[data['comorbidity_count'] < 0]

Empty DataFrame
Columns: [patient_id, age, gender, state, bpl_card, insurance_type, comorbidity_count, prev_admissions, age_group]
Index: []

In [30]:
data['prev_admissions'].describe()
data[data['prev_admissions'] < 0]

Empty DataFrame
Columns: [patient_id, age, gender, state, bpl_card, insurance_type, comorbidity_count, prev_admissions, age_group]
Index: []

In [31]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 86400 entries, 0 to 86399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   patient_id         86400 non-null  str
 1   age                86400 non-null  int64
 2   gender             86400 non-null  str
 3   state              86400 non-null  str
 4   bpl_card           86400 non-null  bool
 5   insurance_type     86400 non-null  str
 6   comorbidity_count  86400 non-null  int64
 7   prev_admissions    86400 non-null  int64
 8   age_group          86400 non-null  category
dtypes: bool(1), category(1), int64(3), str(4)
memory usage: 4.8 MB

In [32]:
data.to_csv("patients_cleaned.csv", index=False)

In [33]:
import os

print(os.path.exists("patients_cleaned.csv"))

True